cluster-name    = "eks-terraform"
accessKey       = ""
secretAccessKey = ""
region          = "us-east-1"
instance-type   = "t2.large"
desired-count   = 1
environment     = "Dev"
owner           = "GaneshM"
purpose         = "HealthcareAPI Platform"
