apiVersion: v1
kind: Service
metadata:
  name: hostdetails-springapp
spec: 
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: NodePort  
  selector:
    app: spring-hostdetails
