FROM node:alpine AS builder

RUN mkdir -p /app

COPY package.json /app

RUN sleep 5s

WORKDIR /app

COPY . .

RUN npm install

RUN npm install -g --save-dev @angular/cli@latest

RUN ng update

RUN npm update

RUN npm install --save-dev @angular-devkit/build-angular

RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist/* /usr/share/nginx/html/

